//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kodmark_arapca.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Indextext {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Indextext() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kodmark_arapca.Resources.Indextext", typeof(Indextext).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قارئات الباركود.
        /// </summary>
        public static string BarkodOkuyucu {
            get {
                return ResourceManager.GetString("BarkodOkuyucu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكسسوارات طابعات الباركود.
        /// </summary>
        public static string BarkodYaziciAksesuar {
            get {
                return ResourceManager.GetString("BarkodYaziciAksesuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملصقات المطبوعة.
        /// </summary>
        public static string BaskiliEtiket {
            get {
                return ResourceManager.GetString("BaskiliEtiket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسمية غير مطبوعة.
        /// </summary>
        public static string BaskisizEtiket {
            get {
                return ResourceManager.GetString("BaskisizEtiket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخلاقيات العمل: تضع اعلى القيم الأخلاقية بنظر الاعتبار في كافة مجالات عملها وقراراتها وعلاقاتها. 
        ///
        ///
        ///الموثوقية: نتعامل بصراحة وصدق ونزاهة وعدالة تجاه بعضنا البعض ومع شركائنا في العمل وعملائنا. اذ تعتبر الثقة والصدق من اهم قيمنا. 
        ///
        ///
        ///الشغف بالنجاح: يمنحنا شغفنا العالي بالنجاح شعوراً يجعلنا نعمل بدافع كبير ونناضل ولا نستسلم امام الصعوبات. 
        ///
        ///
        ///التركيز على الجودة: نقوم بإتمام اعمالنا في وقتها المحدد وبأعلى جودة وكفاءة. 
        ///
        ///المسؤولية: نفهم ما هو مطلوب منا بشكل صحيح ونتحمل المسؤولية فيما يخص عملنا, ونقترح ا [rest of string was truncated]&quot;;.
        /// </summary>
        public static string deger_Text {
            get {
                return ResourceManager.GetString("deger_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيمنا.
        /// </summary>
        public static string değerlerimiz {
            get {
                return ResourceManager.GetString("değerlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطابعات الصناعية.
        /// </summary>
        public static string EndustriyelYazici {
            get {
                return ResourceManager.GetString("EndustriyelYazici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملصقات الفلورسنت.
        /// </summary>
        public static string floresan {
            get {
                return ResourceManager.GetString("floresan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملصقات القابلة للكسر: تسمى بلمصقات الضمان. تنكسر عند محاولة فصلها من المنتج الذي تم لصقها عليه وذلك بفضل مادتها اللاصقة الخاصة.
        ///
        ///ملصقات.
        /// </summary>
        public static string garanti {
            get {
                return ResourceManager.GetString("garanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string garanti2 {
            get {
                return ResourceManager.GetString("garanti2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :VOID.
        /// </summary>
        public static string garanti3 {
            get {
                return ResourceManager.GetString("garanti3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعرف ايضاً بلمصقات الأمان. توجد منها انواع تترك أثراً على سطح الملصق او على السطح الذي توجد فيه وذلك عند إزالتها..
        /// </summary>
        public static string garanti4 {
            get {
                return ResourceManager.GetString("garanti4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملصقات الضمان والأمان.
        /// </summary>
        public static string garantiveGuvenlik {
            get {
                return ResourceManager.GetString("garantiveGuvenlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من نحن.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأسست شركتنا التي تعمل في مجال التعبئة والتغليف سنة 2012 من قبل فريق ذو خبرة خدم في القطاع, وهي تقدم خدماتها في مساحة إجمالية مسقفة تبلغ 1.000م2. 
        ///
        ///
        ///
        ///
        ///تضمن شركتنا إنجاز الأعمال التي على مسؤوليتها وفق القواعد وبجودة عالية وفي الوقت المحدد وذلك بفضل كادرها الديناميكي والمتخصص في مجاله. 
        ///
        ///
        ///
        ///وهي من الشركات الرائدة في إنتاج الملصقات وريبونات النقل الحرارية المستخدمة في كافة القطاعات وفي مقدمتها قطاع الاغذية والكيميائيات والبناء والغزل والنسيج والنقل اللوجستي, بالاضافة الى إنها مؤسسة تقدم بكل ثقة معدات ا [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HakkimizdaYazi_P1 {
            get {
                return ResourceManager.GetString("HakkimizdaYazi_P1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منذ تأسيسها قدمت شركتنا خدماتها داخل البلاد, واعتباراً سنة 2017 بدأت التصدير الى 9 دول. فبالاضافة الى نموها المستمر في تركيا, تواصل شركتنا نجاحاتها في سبيل ان تصبح شركة تسعى دوماً الى التطور وتقترب خطوة بخطوة من هدفها في الوصول الى المزيد من الدول. 
        ///
        ///
        ///
        ///
        ///تقوم شركتنا بالإنتاج وفق معايير الجودة والحساسية تجاه البيئة وذلك تحت ضمان 9001: 2015, وهي تواصل تخصيص ميزانيات كبيرة لمشاريع البحوث-التطوير والإنتاج-التطوير وتقنيات الإنتاج وابحاث التطبيقات الخاصة كي تتمكن من تلبية الاحتياجات العديدة لعملائها وتقديم اج [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HakkimizdaYazi_P2 {
            get {
                return ResourceManager.GetString("HakkimizdaYazi_P2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصالات.
        /// </summary>
        public static string İletisim {
            get {
                return ResourceManager.GetString("İletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤسسية.
        /// </summary>
        public static string Kurumsal {
            get {
                return ResourceManager.GetString("Kurumsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملصقات المطلية.
        /// </summary>
        public static string kuseEtiket {
            get {
                return ResourceManager.GetString("kuseEtiket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملصقات الصاغة والبصريات.
        /// </summary>
        public static string kuyumcu {
            get {
                return ResourceManager.GetString("kuyumcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المهمة.
        /// </summary>
        public static string m {
            get {
                return ResourceManager.GetString("m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعتماد التحسين المستمر مبدأ لها. 
        ///زيادة سعتها الإنتاجية.
        ///إعتماد نظام الإدارة المتجدد والايجابي كأساس لها.
        ///إيلاء الأهمية للجودة.
        /// </summary>
        public static string m_Text {
            get {
                return ResourceManager.GetString("m_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طابعات الباركود المكتبية.
        /// </summary>
        public static string MasaustuYazici {
            get {
                return ResourceManager.GetString("MasaustuYazici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طابعات الباركود المحمولة.
        /// </summary>
        public static string MobilYazici {
            get {
                return ResourceManager.GetString("MobilYazici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP تاير / فاستاير.
        /// </summary>
        public static string ppFastry {
            get {
                return ResourceManager.GetString("ppFastry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملصقات PP اوباك.
        /// </summary>
        public static string ppOpak {
            get {
                return ResourceManager.GetString("ppOpak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انواع الريبون.
        /// </summary>
        public static string RibonCesitleri {
            get {
                return ResourceManager.GetString("RibonCesitleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملصقات Silvermat/ملصقات الاثاث والمعدات.
        /// </summary>
        public static string silvermat {
            get {
                return ResourceManager.GetString("silvermat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملصقات الحرارية.
        /// </summary>
        public static string termal {
            get {
                return ResourceManager.GetString("termal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنتجات.
        /// </summary>
        public static string urunler {
            get {
                return ResourceManager.GetString("urunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرؤية.
        /// </summary>
        public static string v {
            get {
                return ResourceManager.GetString("v", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمع بين جودة المنتجات والخدمات التي يقدمها الكادر المتخصص, كي تتمكن من الوصول الى جماهير واسعة وتصبح الخيار الاول لعملائها..
        /// </summary>
        public static string v_text {
            get {
                return ResourceManager.GetString("v_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملصقات Vellum.
        /// </summary>
        public static string vellum {
            get {
                return ResourceManager.GetString("vellum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رؤيتنا ورسالتنا وقيمنا.
        /// </summary>
        public static string VizyonMisyon {
            get {
                return ResourceManager.GetString("VizyonMisyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطابعات.
        /// </summary>
        public static string Yazıcılar {
            get {
                return ResourceManager.GetString("Yazıcılar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملصقات الأعلاف والاكياس.
        /// </summary>
        public static string yemveCuval {
            get {
                return ResourceManager.GetString("yemveCuval", resourceCulture);
            }
        }
    }
}
